name: refresh site
on:
  push:
    branches:
      - main
#  pull_request:
#    branches:
#      - main
      
jobs:
  refresh-site-job:
    runs-on: ubuntu-latest
    steps:
      - name: Webhook Action
        uses: joelwmale/webhook-action@2.1.0
        with:
          url: ${{ secrets.WEBHOOK_URL }}
